version: '3.3'

services:
  postgres:
    image: postgres:15
    container_name: postgres-server-template-dev
    environment:
      POSTGRES_PASSWORD: passw0rd
      PG_PASSWORD: passw0rd
      POSTGRES_DB: server_db
    ports:
      - "5432:5432"