// Code generated by ent, DO NOT EDIT.

//go:build tools
// +build tools

// Package internal holds a loadable version of the latest schema.
package internal

const Schema = `{"Schema":"server-template/internal/modules/db/schema","Package":"server-template/internal/modules/db/ent","Schemas":[{"name":"Entity","config":{"Table":""},"fields":[{"name":"field","type":{"Type":7,"Ident":"","PkgPath":"","PkgName":"","Nillable":false,"RType":null},"position":{"Index":0,"MixedIn":false,"MixinIndex":0}}]}],"Features":["sql/execquery","sql/upsert","intercept","schema/snapshot"]}`
