// Code generated by ent, DO NOT EDIT.

package entity

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the entity type in the database.
	Label = "entity"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldField holds the string denoting the field field in the database.
	FieldField = "field"
	// Table holds the table name of the entity in the database.
	Table = "entities"
)

// Columns holds all SQL columns for entity fields.
var Columns = []string{
	FieldID,
	FieldField,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Order defines the ordering method for the Entity queries.
type Order func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) Order {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByField orders the results by the field field.
func ByField(opts ...sql.OrderTermOption) Order {
	return sql.OrderByField(FieldField, opts...).ToFunc()
}
